# Generated by Django 2.1.5 on 2019-01-18 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('text', models.TextField()),
                ('h1', models.TextField()),
                ('belon', models.BigIntegerField(default=0)),
                ('date', models.DateField(default=datetime.datetime(2019, 1, 18, 19, 32, 54, 22614))),
                ('enable', models.BigIntegerField(default=0)),
            ],
        ),
    ]
