# Generated by Django 2.1.5 on 2019-01-18 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domapp', '0005_musician'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Musician',
        ),
    ]
