# Generated by Django 2.1.5 on 2019-01-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domapp', '0006_delete_musician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='categories',
            name='h1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='categories',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='categories',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
