# Generated by Django 2.1.5 on 2019-01-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domapp', '0008_categories_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(default='', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(default='', max_length=255)),
                ('h1', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('text', models.TextField(default='')),
                ('belon', models.BigIntegerField(default=0)),
                ('enable', models.BigIntegerField(default=0)),
            ],
        ),
    ]
