# Generated by Django 2.1.5 on 2019-01-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domapp', '0009_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='oldprice',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
    ]
