# Generated by Django 2.1.5 on 2019-01-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domapp', '0010_auto_20190119_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(default='', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(default='', max_length=255)),
                ('h1', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('text', models.TextField(default='')),
                ('text2', models.TextField(default='')),
                ('belon', models.BigIntegerField(default=0)),
                ('enable', models.BigIntegerField(default=0)),
            ],
        ),
    ]
